- repo: wakatime/vim-wakatime
- repo: mfussenegger/nvim-dap
  # hook_post_source: lua require('plugins.dap')
  hook_add: |-
    lua require('plugins.dap')

- repo: rcarriga/nvim-dap-ui
- repo: theHamsta/nvim-dap-virtual-text
- repo: nvim-telescope/telescope-dap.nvim
