- repo: wakatime/vim-wakatime
- repo: github/copilot.vim
- repo: mfussenegger/nvim-dap
  # hook_post_source: lua require('plugins.dap')
  hook_add: |-
    lua require('plugins.dap')

- repo: rcarriga/nvim-dap-ui
- repo: theHamsta/nvim-dap-virtual-text
- repo: nvim-telescope/telescope-dap.nvim
- repo: simrat39/rust-tools.nvim
- repo: nvim-treesitter/nvim-treesitter-context
  depends: nvim-treesitter
